---
title: "Voting"
author: "Alexandra Norris"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(skimr)
library(broom)
```

```{r}
download.file("https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile = "master.zip")

unzip("master.zip")

raw <- read_csv("2018-live-poll-results-master/data/elections-poll-az02-1.csv", col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
))

# read in all of the files

my_list <- fs::dir_ls("2018-live-poll-results-master/data/")

raw <- map_dfr(my_list, .id = "source", read_csv, col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
))


# create a 0/1 variable for dvote for Democratic vote
# create a 0/1 variable female
# relationship between dvote and female


x <- raw %>%
  mutate(dvote = ifelse(response == "Dem", 1, 0),
         female = ifelse(gender == "Female", 1, 0)) %>%
  select(dvote, female, response, gender)

y <- glm(dvote ~ female, data = x, family = "binomial") %>%
  tidy()

y %>%
  ggplot()

```

